version: 1

project:
  root: .
  build_config: lzc-build.yml
  package_file: package.yml
  output: .lazycat-build/writebook.lpk
  target_arch: amd64

update:
  strategy: publish
  allow_downgrade: false
  version_source:
    type: image
    image: writebook
    bump: patch
build:
  run_buildscript: false
images:
  - id: writebook
    target: service
    service: writebook
    source: wulab/writebook
    channel: custom
    sort: created
    tag_regex: '^latest$'
    delivery:
      mode: lazycat
stores:
  official:
    enabled: true
    skip_if_version_exists: true
    changelog_locales: [zh, en]
  private:
    enabled: true
    skip_if_version_exists: true
    name: Writebook
    summary: "Instantly publish your own books on the web"
