application:
  subdomain: writebook
  public_path:
    - /
  upstreams:
    - location: /
      backend: http://writebook:80
services:
  writebook:
    # upstream: wulab/writebook:latest@sha256:1b0a46fc933ec27313ec36de6b6390b79a18d617df661522a6ff8ba5c06b1ae6
    image: registry.lazycat.cloud/czyt/wulab/writebook:54fa01d5f57446ab
    environment:
      - SECRET_KEY_BASE={{ stable_secret "writebook#secret_key" }}
    binds:
      - /lzcapp/var/storage:/rails/storage
    setup_script: |
      mkdir -p /rails/storage/db /rails/storage/files
      chown -R rails:rails /rails/storage
      chown -R 1000:1000 /lzcapp/var/storage
      chmod -R 755 /lzcapp/var/storage
