name: Writebook
package: lazycat.coummunity.app.writebook
version: 1.1.0
min_os_version: 1.3.8
description: Instantly publish your own books on the web
homepage: https://once.com/writebook
author: once
application:
    subdomain: writebook

    public_path:
        - /
    upstreams:
        - location: /
          backend: http://writebook:80

services:
    writebook:
        # wulab/writebook:latest
        image: registry.lazycat.cloud/czyt/wulab/writebook:c5cf4e4ac61d4052
        environment:
            - SECRET_KEY_BASE={{stable_secret "writebook#secret_key"}}
        binds:
            - /lzcapp/var/storage:/rails/storage
        setup_script: |
            mkdir -p /rails/storage/db /rails/storage/files
            chown -R rails:rails /rails/storage
            chown -R 1000:1000 /lzcapp/var/storage
            chmod -R 755 /lzcapp/var/storage

locales:
    zh:
        name: "Writebook"
        description: "随时在网页上发布您自己的书籍"
    zh_CN:
        name: "Writebook"
        description: "随时在网页上发布您自己的书籍"
    en:
        name: "Writebook"
        description: "Instantly publish your own books on the web"
    ja:
        name: "Writebook"
        description: "すぐにウェブ上で自分の本を公開"
